
/********************

Adopted PhyloBayes MPI. https://github.com/bayesiancook/pbmpi
Lartillot, N., Rodrigue, N., Stubbs, D. & Richer, J. 
PhyloBayes MPI: Phylogenetic reconstruction with infinite mixtures of profiles in a parallel environment. Syst. Biol. 62, 611–615 (2013).

**********************/


#ifndef __PARALLELH
#define __PARALLELH 

#include "mpi.h"

const int TAG1 = 95;

enum MESSAGE {KILL,SCAN,UPDATE_RATE,UPDATE_RRATE,UPDATE_BLENGTH,UPDATE_SRATE,UPDATE_SPROFILE,PARAMETER_DIFFUSION,UNFOLD,COLLAPSE,LIKELIHOOD,RESET,MULTIPLY,SMULTIPLY,INITIALIZE,PROPAGATE,PROPOSE,RESTORE,UPDATE,DETACH,ATTACH,NNI,KNIT,BRANCHPROPAGATE,ROOT,REALLOC_MOVE,PROFILE_MOVE,MIX_MOVE,REALLOC_DONE,GIVEMEMORE,BCAST_TREE,GETDIV,UNCLAMP,SETDATA,SETNODESTATES,CVSCORE,SETTESTDATA,GENE_MOVE,SAMPLE,LENGTH,ALPHA,SAVETREES, LENGTHFACTOR, FROMSTREAM, TOSTREAM, SITELOGL, RESTOREDATA, WRITE_MAPPING,NONSYNMAPPING,COUNTMAPPING,SITERATE,SIMULATE,SETRATEPRIOR,SETPROFILEPRIOR,SETROOTPRIOR,UPDATE_ESTRATE,UPDATE_ESTBRANCH,UPDATE_MOVEBRANCH,UPDATE_MOVERATE,UPDATE_MOVEBRAN,UPDATE_MOVEPRRATE,ELBORATEVI,MEANRATEVI,RATEALPHAVI,RATEBETAVI,ELBOLengthVI};

struct prop_arg {
  double time;
  int condalloc;
  int to;
  int from;
};

#endif


